// SPDX-License-Identifier: GPL-3.0-or-later
// Converts the Spectrum 2 design tokens (@adobe/spectrum-tokens,
// dist/json/variables.json) into a C++ table for the app's theme (spec 7,
// "デザイン言語"). Each token is resolved for the light and dark themes at
// the desktop scale; colors become "#AARRGGBB", sizes plain numbers (px).
// Composite tokens (typography, shadows) are skipped.
//
// Usage: spectrum_theme <variables.json> <output.inc>
#include <cctype>
#include <cmath>
#include <cstdio>
#include <fstream>
#include <iostream>
#include <iterator>
#include <nlohmann/json.hpp>
#include <optional>
#include <regex>
#include <set>
#include <sstream>
#include <string>

using nlohmann::json;

namespace {

const json* tokens = nullptr;

std::optional<std::string> Resolve(const std::string& name, const std::string& theme, int depth);

// A token body: a value, a reference, or sets keyed by theme or scale.
std::optional<std::string> ValueOf(const json& body, const std::string& theme, int depth) {
  if (depth > 32) return std::nullopt;  // A reference cycle.
  if (body.contains("value")) {
    const json& value = body["value"];
    if (value.is_number()) return value.dump();
    if (!value.is_string()) return std::nullopt;  // Composite.
    const std::string s = value.get<std::string>();
    if (s.size() > 2 && s.front() == '{' && s.back() == '}') {
      return Resolve(s.substr(1, s.size() - 2), theme, depth + 1);
    }
    return s;
  }
  if (body.contains("sets")) {
    const json& sets = body["sets"];
    for (const char* key : {theme.c_str(), "desktop"}) {
      if (sets.contains(key)) return ValueOf(sets[key], theme, depth + 1);
    }
    return std::nullopt;
  }
  if (body.contains("ref") && body["ref"].is_string()) {
    const std::string ref = body["ref"].get<std::string>();
    if (ref.size() > 2) return Resolve(ref.substr(1, ref.size() - 2), theme, depth + 1);
  }
  return std::nullopt;
}

std::optional<std::string> Resolve(const std::string& name, const std::string& theme, int depth) {
  if (!tokens->contains(name)) return std::nullopt;
  return ValueOf((*tokens)[name], theme, depth);
}

std::string CamelCase(const std::string& name) {
  std::string result;
  bool upper = false;
  for (char c : name) {
    if (c == '-') {
      upper = true;
      continue;
    }
    result += upper ? static_cast<char>(std::toupper(static_cast<unsigned char>(c))) : c;
    upper = false;
  }
  return result;
}

enum class Kind { kColor, kNumber, kString };

// Normalizes a raw value: colors to #AARRGGBB, px and plain numbers to a
// number.
std::pair<Kind, std::string> Convert(const std::string& raw) {
  static const std::regex rgb(
      R"(rgba?\(\s*([\d.]+)\s*,\s*([\d.]+)\s*,\s*([\d.]+)\s*(?:,\s*([\d.]+)\s*)?\))");
  static const std::regex number(R"((-?[\d.]+)(px)?)");
  std::smatch m;
  if (std::regex_match(raw, m, rgb)) {
    const double alpha = m[4].matched ? std::stod(m[4].str()) : 1.0;
    char hex[10];
    std::snprintf(hex, sizeof hex, "#%02x%02x%02x%02x", static_cast<int>(std::lround(alpha * 255)),
                  std::stoi(m[1].str()), std::stoi(m[2].str()), std::stoi(m[3].str()));
    return {Kind::kColor, hex};
  }
  if (std::regex_match(raw, m, number)) return {Kind::kNumber, m[1].str()};
  return {Kind::kString, raw};
}

std::string Quoted(const std::string& s) {
  std::string out = "\"";
  for (char c : s) {
    if (c == '"' || c == '\\') out += '\\';
    out += c;
  }
  return out + "\"";
}

}  // namespace

int main(int argc, char** argv) {
  if (argc != 3) {
    std::cerr << "usage: spectrum_theme <variables.json> <output.inc>\n";
    return 2;
  }
  std::ifstream in(argv[1]);
  if (!in) {
    std::cerr << "cannot read " << argv[1] << "\n";
    return 1;
  }
  const json document = json::parse(in);
  tokens = &document;

  std::ostringstream out;
  out << "// Generated by tools/spectrum_theme from @adobe/spectrum-tokens (Apache-2.0).\n"
         "// Do not edit. {name, kind, light, dark}; kind: c color, n number, s string.\n";
  std::set<std::string> names;
  int count = 0;
  for (const auto& [name, body] : document.items()) {
    const auto light = Resolve(name, "light", 0);
    const auto dark = Resolve(name, "dark", 0);
    if (!light || !dark) continue;
    const auto [kind, light_value] = Convert(*light);
    const auto [dark_kind, dark_value] = Convert(*dark);
    if (kind != dark_kind) continue;
    const std::string camel = CamelCase(name);
    if (!names.insert(camel).second) continue;
    const char k = kind == Kind::kColor ? 'c' : kind == Kind::kNumber ? 'n' : 's';
    out << "{" << Quoted(camel) << ", '" << k << "', " << Quoted(light_value) << ", "
        << Quoted(dark_value) << "},\n";
    ++count;
  }

  std::ofstream file(argv[2], std::ios::binary);
  file << out.str();
  std::cout << "spectrum_theme: " << count << " tokens\n";
  return 0;
}
